### ISSUE TITLE
Sorry,I cound not find the script to create  "go.norm" file.

### ISSUE THREAD

**Issue by CNwangbin** [bio-ontology-research-group/deepgozero#1]

**Comment by coolmaksat** [comment]
Hi,
Please run groovy Normalizer.groovy -i data/go.owl -o data/go.norm

**Comment by CNwangbin** [comment]
> 

Ok,Thanks.

**Comment by CNwangbin** [comment]
When I try to run this cmd both on win10&Linux,it seem to have a class not find error.
![image](https://user-images.githubusercontent.com/87804802/156372918-e10fd546-b5be-48a9-a341-81fd90b6eb57.png)

**Comment by leechuck** [comment]
Could you please provide the output of `groovy --version` ?

**Comment by coolmaksat** [comment]
I added  commons-cli library to grab list. Please update the script and try again.

**Comment by CNwangbin** [comment]
> I added commons-cli library to grab list. Please update the script and try again.

Yes, I update the script and run the command ,the same error occured.My machine installed JAVA-JDK8 and I downloaded the "go.owl" file from GO Website, I missed some dependencies?

**Comment by CNwangbin** [comment]
> 

![image](https://user-images.githubusercontent.com/87804802/156480881-f4fe1969-fa6d-403d-9fe8-8cefba195e4f.png)
Thanks,this is the version info.

**Comment by CNwangbin** [comment]
The same error occured in my Win10 enveriment.
![image](https://user-images.githubusercontent.com/87804802/156485333-70c07dc3-ab93-40d6-96db-477fa59373b2.png)

**Comment by coolmaksat** [comment]
Could you please install groovy version 2.4. It seems CliBuilder is not available in 4.0

**Comment by coolmaksat** [comment]
Alternatively, you can download the version we use from here https://deepgo.cbrc.kaust.edu.sa/data/deepgozero/data/go.norm
Also, download go.obo and go.owl from there

**Comment by CNwangbin** [comment]
> Alternatively, you can download the version we use from here https://deepgo.cbrc.kaust.edu.sa/data/deepgozero/data/go.norm Also, download go.obo and go.owl from thereI
I'm grateful for your help.When I installed groovy v-2.4, the old bug fixed but a new bug occured.Now, I used the alternative "go.norm" file which you provided.Thanks for your patient tutorial!

**Comment by CNwangbin** [comment]
Hi, what is the definitions_go.txt file used for?

**Comment by CNwangbin** [comment]
![image](https://user-images.githubusercontent.com/87804802/172162228-251cc1e7-1668-4481-bf18-7025c3207562.png)
I get a error when run the script.

**Comment by coolmaksat** [comment]
It seems you need to increase java heap memory

**Comment by CNwangbin** [comment]
> It seems you need to increase java heap memory

Thanks for your reply, It could aright generate go.norm file.But there are also some bugs information, is that some problem?
![image](https://user-images.githubusercontent.com/87804802/172319272-aaf3b816-2722-49f0-9c0d-57ba41870792.png)

**Comment by coolmaksat** [comment]
No, this is fine.

**Comment by CNwangbin** [comment]
> > It seems you need to increase java heap memory
> 
> Thanks for your reply, It could aright generate go.norm file.But there are also some bugs information, is that some problem? ![image](https://user-images.githubusercontent.com/87804802/172319272-aaf3b816-2722-49f0-9c0d-57ba41870792.png)
set JAVA heap space.
`$set JAVA_OPTS=-server -Xms6000m -Xmx6000m -XX:MaxNewSize=3096m -XX:MaxPermSize=3096m`

**Comment by altriasjy31** [comment]
I also get a similar error when I run Normalizer.groovy.
the version of groovy is 2.4，the system version is wsl-ubuntu 22.04

groovy -i data/go.owl -o data/go.norm

> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> Caught: java.lang.ExceptionInInitializerError
> java.lang.ExceptionInInitializerError
>         at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:67)
>         at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:72)
>         at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
>         at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:216)
>         at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:64)
>         at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:204)
>         at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.<init>(ProviderMethod.java:256)
>         at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:71)
>         at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:275)
>         at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:144)
>         at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123)
>         at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
>         at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:349)
>         at com.google.inject.spi.Elements.getElements(Elements.java:110)
>         at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
>         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
>         at com.google.inject.Guice.createInjector(Guice.java:96)
>         at com.google.inject.Guice.createInjector(Guice.java:73)
>         at com.google.inject.Guice.createInjector(Guice.java:62)
>         at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:91)
>         at org.semanticweb.owlapi.apibinding.OWLManager.instatiateOWLOntologyManager(OWLManager.java:103)
>         at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:58)
>         at org.semanticweb.owlapi.apibinding.OWLManager$createOWLOntologyManager.call(Unknown Source)
>         at Normalizer.run(Normalizer.groovy:63)
>         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @61443d8f
>         at com.google.inject.internal.cglib.core.$ReflectUtils$2.run(ReflectUtils.java:56)
>         at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:46)
>         ... 25 more

**Comment by CNwangbin** [comment]
> I also get a similar error when I run Normalizer.groovy. the version of groovy is 2.4，the system version is wsl-ubuntu 22.04
> 
> groovy -i data/go.owl -o data/go.norm
> 
> > SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> > SLF4J: Defaulting to no-operation (NOP) logger implementation
> > SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> > Caught: java.lang.ExceptionInInitializerError
> > java.lang.ExceptionInInitializerError
> > at com.google.inject.internal.cglib.reflect.$FastClassEmitter.(FastClassEmitter.java:67)
> > at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:72)
> > at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
> > at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:216)
> > at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:64)
> > at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:204)
> > at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.(ProviderMethod.java:256)
> > at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:71)
> > at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:275)
> > at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:144)
> > at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123)
> > at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
> > at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:349)
> > at com.google.inject.spi.Elements.getElements(Elements.java:110)
> > at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
> > at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
> > at com.google.inject.Guice.createInjector(Guice.java:96)
> > at com.google.inject.Guice.createInjector(Guice.java:73)
> > at com.google.inject.Guice.createInjector(Guice.java:62)
> > at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:91)
> > at org.semanticweb.owlapi.apibinding.OWLManager.instatiateOWLOntologyManager(OWLManager.java:103)
> > at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:58)
> > at org.semanticweb.owlapi.apibinding.OWLManager$createOWLOntologyManager.call(Unknown Source)
> > at Normalizer.run(Normalizer.groovy:63)
> > at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> > Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @61443d8f
> > at com.google.inject.internal.cglib.core.$ReflectUtils$2.run(ReflectUtils.java:56)
> > at com.google.inject.internal.cglib.core.$ReflectUtils.(ReflectUtils.java:46)
> > ... 25 more

I think this command could help you to fix the bug.
https://github.com/bio-ontology-research-group/deepgozero/issues/1#issuecomment-1236570938

**Comment by altriasjy31** [comment]
Solved, change jdk-17 to jdk-11 to run successfully

`groovy Normalizer.groovy -i data/go.owl -o data/go.norm `

> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> Ignoring SubObjectPropertyOf*(8 10):The translation map is incomplete. Item id was not found: '8'.
> Ignoring SubObjectPropertyOf*(9 10):The translation map is incomplete. Item id was not found: '9'.
> Ignoring SubObjectPropertyOf*(6 12):The translation map is incomplete. Item id was not found: '6'.
